<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\User;
use App\Models\Post;
use Illuminate\Support\Facades\DB;
use \Datetime;

class PostSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('posts')->insert([
            [
                'user_id' => 1,
                'title' => "Cho thuê phòng trọ 18m2 khép kín sát chợ Hôm ngõ 76 phố Trần Xuân Soạn HBT, full đồ vào ở ngay",
                "address" => "76 phố Trần Xuân Soạn, HBT, Hà Nội",
                "street" => "76 Trần Xuân Soạn",
                "ward" => "Ngô Thì Nhậm",
                "district" => "Hai Bà Trưng",
                "price" => 2800000,
                "land_area" => 18,
                "type" => 1,
                "view_number" => 150,
                "description" => "Cho thuê phòng trọ sát chợ Hôm ngõ 76 phố Trần Xuân Soạn, HBT, Hà Nội.
                DT 18m² khép kín, đầy đủ tiên nghi gồm tủ lạnh, bình nóng lạnh, điều hoà, vs khép kín. Vào ở ngay.
                Thu tiền nhà tháng một lần. Không ở chung với chủ nhà. Ưu tiên cho người đi làm, hay ở một mình.
                Giá 2.8tr/tháng.
                Nhà ko có chỗ để xe máy, khách tự liên hệ chỗ gửi ngay chợ Hôm, giá trên chưa có tiền điện, nước và vệ sinh.
                Cho thuê lâu dài.",
                "bedroom_num" => 1,
                "bathroom_num" => 1,
                "latitude" => 21.01696411765529,
                "longitude" => 105.85215587641993,
                "created_at" => (new DateTime())->modify("- 10 days"),
                "updated_at" => (new DateTime())->modify("- 10 days"),
            ],
            [
                'user_id' => 2,
                'title' => "Chính chủ cần cho thuê gấp nhà riêng mặt ngõ to Trần Khát Chân, ô tô ra vào thoải mái",
                "address" => "Số 21 ngõ 461, Đường Trần Khát Chân, Phường Thanh Nhàn, Hai Bà Trưng, Hà Nội",
                "street" => "461 Trần Khát Chân",
                "ward" => "Thanh Nhàn",
                "district" => "Hai Bà Trưng",
                "price" => 7000000,
                "land_area" => 30,
                "type" => 2,
                "view_number" => 289,
                "description" => "Tôi cần cho thuê nhà số 21 ngõ 461 phố Trần Khát Chân, gần phố Huế, mặt ngõ to, cách đường chính 10m, ôtô đỗ cửa. Thích hợp cho hộ gia đình thuê hoặc làm văn phòng, kinh doanh online thoải mái.
                DT: 30 m² x 2 tầng, 3 mặt thoáng. Bếp, điện, nước tốt, có ĐH, NL, phụ khép kín, chính chủ.
                Giá chỉ 7tr/ tháng (có thương lượng).",
                "bedroom_num" => 3,
                "bathroom_num" => 1,
                "latitude" => 21.008412668682436,
                "longitude" => 105.85333818226412,
                "created_at" => (new DateTime())->modify("- 5 days"),
                "updated_at" => (new DateTime())->modify("- 5 days"),
            ],
            [
                'user_id' => 3,
                'title' => "Chính chủ cho thuê phòng 1K1N hơn 50m2 đủ đồ tại đoạn Trần Đại Nghĩa kéo dài, gần Nguyễn An Ninh",
                "address" => "102 Phố Trần Đại Nghĩa, Phường Đồng Tâm, Hai Bà Trưng, Hà Nội",
                "street" => "102 Trần Đại Nghĩa",
                "ward" => "Đồng Tâm",
                "district" => "Hai Bà Trưng",
                "price" => 7500000,
                "land_area" => 50,
                "type" => 1,
                "view_number" => 287,
                "description" => "Nhà mình còn một phòng tầng 2 trong nhà 3 tầng cần cho thuê.
                Phòng rộng, thoáng (hơn 50m²) thiết kế 1 khách, 1 ngủ, có thể chuyển đổi công năng thành 2 ngủ.
                Nội thất đầy đủ: Điều hoà, nóng lạnh, bếp, sofa, giường tủ (như hình).
                Giá thuê: 7 - 7tr5/tháng.",
                "bedroom_num" => 2,
                "bathroom_num" => 1,
                "latitude" => 20.998174179206124,
                "longitude" => 105.84618766138327,
                "created_at" => (new DateTime())->modify("- 15 days"),
                "updated_at" => (new DateTime())->modify("- 15 days"),
            ],
            [
                'user_id' => 4,
                'title' => "Cho thuê Ký túc xá-sleepbox Minh Khai tiện nghi gần Đại học Kih tế quốc dân, XD, Bk, . Giá từ 1tr5",
                "address" => "160 Minh Khai, Phường Minh Khai, Hai Bà Trưng, Hà Nội",
                "street" => "160 Minh Khai",
                "ward" => "Minh Khai",
                "district" => "Hai Bà Trưng",
                "price" => 1500000,
                "land_area" => 10,
                "type" => 1,
                "view_number" => 500,
                "description" => "Cho thuê Ký túc xá-sleepbox Minh Khai tiện nghi gần Đại học Kih tế quốc dân, XD, Bk, . Giá từ 1tr5
                - Vị trí: Ngõ 160 Minh Khai, cách mặt phố minh Khai 60m đi bộ 2 phút bắt được xe buýt
                - Trang bị bàn học, kệ sách và tủ đồ cá nhân riêng biệt
                - Có bếp chung free
                - Free điện, nước, wifi, máy giặt, máy lạnh
                - Có nhân viên dọn vệ sinh hàng tuần",
                "bedroom_num" => 1,
                "bathroom_num" => 0,
                "latitude" => 20.996060934023543,
                "longitude" => 105.857414,
                "created_at" => (new DateTime())->modify("- 13 days"),
                "updated_at" => (new DateTime())->modify("- 13 days"),
            ],
            [
                'user_id' => 5,
                'title' => "Cho thuê nhà xây mới, công trình phụ khép kín, gần Times City",
                "address" => "421 Đường Minh Khai, Phường Vĩnh Tuy, Hai Bà Trưng, Hà Nội.",
                "street" => "421 Minh Khai",
                "ward" => "Vĩnh Tuy",
                "district" => "Hai Bà Trưng",
                "price" => 3500000,
                "land_area" => 30,
                "type" => 2,
                "view_number" => 500,
                "description" => "Cho thuê nhà trọ, công trình phụ khép kín. Thoáng mát, sáng, có điều hoà, bình nước nóng lạnh, vị trí tiện ích, có chỗ để xe, truyền hình cáp TW. An ninh tốt. Giao thông thuận tiện đầu cầu Vĩnh Tuy, gần Times City. Ra trung tâm TP khoảng 10 phút.
                Giá 3,5tr đồng/tháng trở lên. Đặt cọc trước 1 tháng. Thanh toán 3 tháng/lần. Ưu tiên hộ gia đình & nữ.",
                "bedroom_num" => 1,
                "bathroom_num" => 1,
                "latitude" => 20.997753803465898,
                "longitude" => 105.86682908465419,
                "created_at" => (new DateTime())->modify("- 1 days"),
                "updated_at" => (new DateTime())->modify("- 1 days"),
            ],
            [
                'user_id' => 6,
                'title' => "Cho thuê nhà riêng 4 tầng ở ngõ 191 Đại La - Hai Bà Trưng",
                "address" => "Ngõ 191, Phố Đại La, Phường Trương Định, Hai Bà Trưng, Hà Nội",
                "street" => "191 Đại La",
                "ward" => "Trương Định",
                "district" => "Hai Bà Trưng",
                "price" => 5500000,
                "land_area" => 112,
                "type" => 2,
                "view_number" => 510,
                "description" => "Mình có nhà riêng muốn cho thuê DT 28m² x 4 tầng.
                Giá 5.5 triệu/tháng, gồm 3 phòng ngủ, 3WC, 1PK, 1 bếp. Trong nhà có đầy đủ tiện nghi ĐH, NL, MG, giường, tủ bếp.
                ĐC: Ngõ 191 Đại La.",
                "bedroom_num" => 3,
                "bathroom_num" => 3,
                "latitude" => 20.996349868212928,
                "longitude" => 105.84586108465419,
                "created_at" => (new DateTime())->modify("+ 1 days"),
                "updated_at" => (new DateTime())->modify("+ 1 days"),
            ],
            [
                'user_id' => 7,
                'title' => "Cho thuê nhà riêng 4 tầng ở ngõ 345, Trần Khát Chân",
                "address" => "345 Trần Khát Chân, Thanh Nhàn, Hai Bà Trưng, Hà Nội",
                "street" => "345 Trần Khát Chân",
                "ward" => "Thanh Nhàn",
                "district" => "Hai Bà Trưng",
                "price" => 7000000,
                "land_area" => 88,
                "type" => 2,
                "view_number" => 376,
                "description" => "Cho thuê nhà riêng biệt 4 tầng, 22m²/tầng, có điều hòa các phòng, nóng lạnh, bếp ga âm, máy giặt, nội thất hiện đại, sàn gỗ phòng ngủ.
                Ngõ rộng ô tô đỗ cửa tiện làm VP + ở, điện nước công tơ riêng giá nhà nước.
                ĐC: Ngõ 345, Trần Khát Chân cũ (bây giờ là phố Lạc Nghiệp).
                Giá: 7 tr/tháng.",
                "bedroom_num" => 4,
                "bathroom_num" => 4,
                "latitude" => 21.008948874977467,
                "longitude" => 105.85962525396255,
                "created_at" => (new DateTime())->modify("- 9 days"),
                "updated_at" => (new DateTime())->modify("- 9 days"),
            ],
            [
                'user_id' => 8,
                'title' => "Cho thuê nhà riêng 3 tầng ở ngõ 15, Đê Tô Hoàng",
                "address" => "Ngõ 15, Đường Đê Tô Hoàng, Phường Bạch Mai, Hai Bà Trưng, Hà Nội",
                "street" => "Ngõ 15 Đê Tô Hoàng",
                "ward" => "Bạch Mai",
                "district" => "Hai Bà Trưng",
                "price" => 4500000,
                "land_area" => 30,
                "type" => 2,
                "view_number" => 230,
                "description" => "Cho thuê nhà trọ, công trình phụ khép kín. Thoáng mát, sáng, có điều hoà, bình nước nóng lạnh, vị trí tiện ích, có chỗ để xe, truyền hình cáp TW. An ninh tốt. Giao thông thuận tiện đầu cầu Vĩnh Tuy, gần Times City. Ra trung tâm TP khoảng 10 phút.
                Giá 3,5tr đồng/tháng trở lên. Đặt cọc trước 1 tháng. Thanh toán 3 tháng/lần. Ưu tiên hộ gia đình & nữ.",
                "bedroom_num" => 2,
                "bathroom_num" => 1,
                "latitude" => 21.007243000000006,
                "longitude" => 105.84954325396255,
                "created_at" => (new DateTime())->modify("- 3 days"),
                "updated_at" => (new DateTime())->modify("- 3 days"),
            ],
            [
                'user_id' => 9,
                'title' => "Mới 100%, cho thuê chung cư mini phường Minh Khai đầy đủ nội thất. Còn 1 phòng duy nhất!",
                "address" => "Ngõ 77, Phố 8/3, Phường Minh Khai, Hai Bà Trưng, Hà Nội",
                "street" => "Ngõ 77 8/3",
                "ward" => "Minh Khai",
                "district" => "Hai Bà Trưng",
                "price" => 6000000,
                "land_area" => 33,
                "type" => 3,
                "view_number" => 1009,
                "description" => "Nhà mới hoàn thiện mà không tranh thủ là hết!

                Nhà mới toanh có thang máy hiện đại địa chỉ ở ngõ 77 phố 8/3 phù hợp với gia đình, sinh viên, người đi làm.

                - Phòng có diện tích sử dụng DT 33m² (có ban công riêng rộng rãi phơi đồ thoải mái, có kho chứa đồ riêng).
                Điện 2k8/số. Nước và rác 100k/người/tháng. Dịch vụ 100k/người/tháng. Internet (gồm cả dây và wifi) 100k/phòng/tháng.",
                "bedroom_num" => 1,
                "bathroom_num" => 1,
                "latitude" => 20.998668065287493,
                "longitude" => 105.86044708465418,
                "created_at" => (new DateTime())->modify("- 4 days"),
                "updated_at" => (new DateTime())->modify("- 4 days"),
            ],
            [
                'user_id' => 10,
                'title' => "Chính chủ cho thuê chung cư mini tại Lạc Trung Quận Hai Bà Trưng. Giá từ 6tr/phòng mới 100% đủ đồ",
                "address" => "Số 65 ngõ 19, Phố Lạc Trung, Phường Vĩnh Tuy, Hai Bà Trưng, Hà Nội",
                "street" => "19 Lạc Trung",
                "ward" => "Vĩnh Tuy",
                "district" => "Hai Bà Trưng",
                "price" => 6000000,
                "land_area" => 24,
                "type" => 3,
                "view_number" => 1500,
                "description" => "Chính chủ cho thuê phòng tại: Số 65 ngõ 19 Lạc Trung, Q. Hai Bà Trưng, HN.
                Giá từ: 5tr đến 6tr.
                Phòng mới xây có gác xép, ban công, ô cửa thoáng, có thang máy, hệ thống PCCC tiêu chuẩn theo quy định hiện hành.
                Nội thất:
                Gác xép, điều hòa, nóng lạnh, tủ quần áo, kệ bếp, bếp từ đôi, hút mùi, tủ bếp: Có sẵn.
                Tủ lạnh: Thêm 200K/tháng, máy giặt riêng: Thêm 300k/tháng.
                Dịch vụ:
                Điện: 3,8K/số.
                Nước: 30K/m3.",
                "bedroom_num" => 1,
                "bathroom_num" => 1,
                "latitude" => 21.002986000000003,
                "longitude" => 105.865675,
                "created_at" => (new DateTime())->modify("- 12 days"),
                "updated_at" => (new DateTime())->modify("- 12 days"),
            ],
            [
                'user_id' => 1,
                'title' => "Cho thuê phòng trọ 20m2 gần Times City, có nội thất đầy đủ",
                "address" => "12 ngách 36/17 phố Minh Khai, Trương Định, Hai Bà Trưng, Hà Nội",
                "street" => "36/17 Minh Khai",
                "ward" => "Trương Định",
                "district" => "Hai Bà Trưng",
                "price" => 3200000,
                "land_area" => 20,
                "type" => 1,
                "view_number" => 180,
                "description" => "Phòng trọ 20m² gần Times City, có đầy đủ nội thất: tủ lạnh, máy lạnh, bình nóng lạnh, giường, tủ quần áo. Thuận tiện di chuyển, an ninh tốt. Giá thuê 3.2 triệu/tháng.",
                "bedroom_num" => 1,
                "bathroom_num" => 1,
                "latitude" => 20.99570062840581,
                "longitude" => 105.85062754170967,
                "created_at" => (new DateTime())->modify("- 8 days"),
                "updated_at" => (new DateTime())->modify("- 8 days"),
            ],
            [
                'user_id' => 2,
                'title' => "Căn hộ mini mới xây, gần trường ĐH Bách Khoa Hà Nội",
                "address" => "45 ngõ 78 Đại Cồ Việt, Lê Đại Hành, Hai Bà Trưng, Hà Nội",
                "street" => "78 Đại Cồ Việt",
                "ward" => "Lê Đại Hành",
                "district" => "Hai Bà Trưng",
                "price" => 3800000,
                "land_area" => 25,
                "type" => 3,
                "view_number" => 250,
                "description" => "Căn hộ mini mới xây, gần trường ĐH Bách Khoa Hà Nội. Nội thất hiện đại, đầy đủ tiện nghi. Diện tích 25m², phòng rộng rãi, thoáng đãng. Giá thuê 3.8 triệu/tháng.",
                "bedroom_num" => 1,
                "bathroom_num" => 1,
                "latitude" => 21.008455421542802,
                "longitude" => 105.847377528878,
                "created_at" => (new DateTime())->modify("- 12 days"),
                "updated_at" => (new DateTime())->modify("- 12 days"),
            ],
            [
                'user_id' => 3,
                'title' => "Cho thuê nhà nguyên căn 3 tầng gần khu vực trung tâm",
                "address" => "125 phố Tân Mai, Tân Mai, Hoàng Mai, Hà Nội",
                "street" => "125 Tân Mai",
                "ward" => "Tân Mai",
                "district" => "Hoàng Mai",
                "price" => 5800000,
                "land_area" => 60,
                "type" => 2,
                "view_number" => 320,
                "description" => "Nhà nguyên căn 3 tầng gần khu vực trung tâm. Diện tích 60m², gồm 2 phòng ngủ, 2 nhà vệ sinh, phòng khách, bếp. Đầy đủ nội thất, tiện nghi. Giá thuê 5.8 triệu/tháng.",
                "bedroom_num" => 2,
                "bathroom_num" => 2,
                "latitude" => 20.983845169049584,
                "longitude" => 105.84894545963832,
                "created_at" => (new DateTime())->modify("- 6 days"),
                "updated_at" => (new DateTime())->modify("- 6 days"),
            ],
            [
                'user_id' => 4,
                'title' => "Cho thuê căn hộ mini gần bến xe Giáp Bát",
                "address" => "31 ngõ 18 Đại La, Trương Định, Hai Bà Trưng, Hà Nội",
                "street" => "18 Đại La",
                "ward" => "Trương Định",
                "district" => "Hai Bà Trưng",
                "price" => 3500000,
                "land_area" => 28,
                "type" => 3,
                "view_number" => 180,
                "description" => "Căn hộ mini gần bến xe Giáp Bát, diện tích 28m², phòng rộng rãi, thoáng đãng. Gần trung tâm, tiện ích xung quanh đầy đủ. Giá thuê 3.5 triệu/tháng.",
                "bedroom_num" => 1,
                "bathroom_num" => 1,
                "latitude" => 20.995929655885213,
                "longitude" => 105.84907679780073,
                "created_at" => (new DateTime())->modify("- 10 days"),
                "updated_at" => (new DateTime())->modify("- 10 days"),
            ],
            [
                'user_id' => 5,
                'title' => "Cho thuê phòng trọ mới xây gần Đại học Kinh Tế Quốc Dân",
                "address" => "79 ngách 32 ngõ 45 Lê Văn Hưu, Ngô Thì Nhậm, Hai Bà Trưng, Hà Nội",
                "street" => "45 Lê Văn Hưu",
                "ward" => "Ngô Thì Nhậm",
                "district" => "Hai Bà Trưng",
                "price" => 2900000,
                "land_area" => 18,
                "type" => 1,
                "view_number" => 210,
                "description" => "Phòng trọ mới xây gần Đại học Kinh Tế Quốc Dân. Diện tích 18m², tiện nghi đầy đủ: giường, tủ, bình nóng lạnh, điều hòa. Giá thuê 2.9 triệu/tháng.",
                "bedroom_num" => 1,
                "bathroom_num" => 1,
                "latitude" => 21.0180612428691,
                "longitude" => 105.85336499959556,
                "created_at" => (new DateTime())->modify("- 7 days"),
                "updated_at" => (new DateTime())->modify("- 7 days"),
            ],
            [
                'user_id' => 6,
                'title' => "Cho thuê nhà nguyên căn gần trường ĐH Bách Khoa",
                "address" => "87 ngách 75/18 Đại Cồ Việt, Bách Khoa, Hai Bà Trưng, Hà Nội",
                "street" => "75/18 Đại Cồ Việt",
                "ward" => "Bách Khoa",
                "district" => "Hai Bà Trưng",
                "price" => 6500000,
                "land_area" => 45,
                "type" => 2,
                "view_number" => 280,
                "description" => "Nhà nguyên căn gần trường ĐH Bách Khoa. Diện tích 45m², 3 tầng, 3 phòng ngủ, 2 nhà vệ sinh, nội thất đầy đủ. Giá thuê 6.5 triệu/tháng.",
                "bedroom_num" => 3,
                "bathroom_num" => 2,
                "latitude" => 21.00777798678856,
                "longitude" => 105.84623805894353,
                "created_at" => (new DateTime())->modify("- 9 days"),
                "updated_at" => (new DateTime())->modify("- 9 days"),
            ],
            [
                'user_id' => 7,
                'title' => "Cho thuê căn hộ mini đầy đủ tiện nghi gần Times City",
                "address" => "9 ngõ 15 Đền Lừ, Hoàng Văn Thụ, Hai Bà Trưng, Hà Nội",
                "street" => "15 Đền Lừ",
                "ward" => "Hoàng Văn Thụ",
                "district" => "Hai Bà Trưng",
                "price" => 4000000,
                "land_area" => 32,
                "type" => 3,
                "view_number" => 230,
                "description" => "Căn hộ mini đầy đủ tiện nghi gần Times City. Diện tích 32m², có ban công, nội thất đầy đủ. Giá thuê 4 triệu/tháng.",
                "bedroom_num" => 1,
                "bathroom_num" => 1,
                "latitude" => 20.985672929728597,
                "longitude" => 105.86149223203064,
                "created_at" => (new DateTime())->modify("- 8 days"),
                "updated_at" => (new DateTime())->modify("- 8 days"),
            ],
            [
                'user_id' => 8,
                'title' => "Cho thuê nhà nguyên căn 3 tầng gần cầu Vĩnh Tuy",
                "address" => "31 ngõ 47 Hoàng Cầu, Chợ Dừa, Đống Đa, Hà Nội",
                "street" => "47 Hoàng Cầu",
                "ward" => "Chợ Dừa",
                "district" => "Đống Đa",
                "price" => 6200000,
                "land_area" => 55,
                "type" => 2,
                "view_number" => 290,
                "description" => "Nhà nguyên căn 3 tầng. Diện tích 55m², 3 phòng ngủ, 2 nhà vệ sinh, nội thất đầy đủ. Giá thuê 6.2 triệu/tháng.",
                "bedroom_num" => 3,
                "bathroom_num" => 2,
                "latitude" => 21.01914804591521,
                "longitude" => 105.82519785620197,
                "created_at" => (new DateTime())->modify("- 10 days"),
                "updated_at" => (new DateTime())->modify("- 10 days"),
            ],
            [
                'user_id' => 9,
                'title' => "Cho thuê căn hộ mini tiện nghi gần bến xe Giáp Bát",
                "address" => "72 ngõ 29 Đại La, Trương Định, Hai Bà Trưng, Hà Nội",
                "street" => "29 Đại La",
                "ward" => "Trương Định",
                "district" => "Hai Bà Trưng",
                "price" => 7800000,
                "land_area" => 25,
                "type" => 3,
                "view_number" => 180,
                "description" => "Căn hộ mini tiện nghi gần bến xe Giáp Bát. Diện tích 25m², phòng sáng sạch, nội thất đầy đủ. Giá thuê 3.8 triệu/tháng.",
                "bedroom_num" => 1,
                "bathroom_num" => 1,
                "latitude" => 20.99631814280486,
                "longitude" => 105.84787430167958,
                "created_at" => (new DateTime())->modify("- 12 days"),
                "updated_at" => (new DateTime())->modify("- 12 days"),
            ],
            [
                'user_id' => 10,
                'title' => "Cho thuê phòng trọ đẹp gần ĐH Bách Khoa Hà Nội",
                "address" => "15 ngõ 83 Đại Cồ Việt, Lê Đại Hành, Hai Bà Trưng, Hà Nội",
                "street" => "83 Đại Cồ Việt",
                "ward" => "Lê Đại Hành",
                "district" => "Hai Bà Trưng",
                "price" => 3000000,
                "land_area" => 20,
                "type" => 1,
                "view_number" => 220,
                "description" => "Phòng trọ đẹp gần ĐH Bách Khoa Hà Nội. Diện tích 20m², nội thất cơ bản, sạch sẽ. Giá thuê 3 triệu/tháng.",
                "bedroom_num" => 1,
                "bathroom_num" => 1,
                "latitude" => 21.008926180320326,
                "longitude" => 105.85084473109761,
                "created_at" => (new DateTime())->modify("- 15 days"),
                "updated_at" => (new DateTime())->modify("- 15 days"),
            ],
            [
                'user_id' => 1,
                'title' => "Cho thuê căn hộ mini gần trường THPT Chuyên Hà Nội-Amsterdam",
                "address" => "28 ngõ 17 Đặng Tiến Đông, Trung Liệt, Đống Đa, Hà Nội",
                "street" => "17 Đặng Tiến Đông",
                "ward" => "Trung Liệt",
                "district" => "Đống Đa",
                "price" => 4200000,
                "land_area" => 30,
                "type" => 3,
                "view_number" => 190,
                "description" => "Căn hộ mini gần trường THPT Chuyên Hà Nội-Amsterdam. Diện tích 30m², tiện nghi đầy đủ, sạch sẽ. Giá thuê 4.2 triệu/tháng.",
                "bedroom_num" => 1,
                "bathroom_num" => 1,
                "latitude" => 21.01097961610902,
                "longitude" => 105.82485435929077,
                "created_at" => (new DateTime())->modify("- 18 days"),
                "updated_at" => (new DateTime())->modify("- 18 days"),
            ],
            [
                'user_id' => 2,
                'title' => "Cho thuê phòng trọ sạch sẽ gần trường ĐH Bách Khoa",
                "address" => "64 ngõ 29 Lê Thanh Nghị, Đồng Tâm, Hai Bà Trưng, Hà Nội",
                "street" => "29 Lê Thanh Nghị",
                "ward" => "Đồng Tâm",
                "district" => "Hai Bà Trưng",
                "price" => 3500000,
                "land_area" => 22,
                "type" => 1,
                "view_number" => 240,
                "description" => "Phòng trọ sạch sẽ gần trường ĐH Bách Khoa. Diện tích 22m², đầy đủ tiện nghi. Giá thuê 3.5 triệu/tháng.",
                "bedroom_num" => 1,
                "bathroom_num" => 1,
                "latitude" => 21.00103457391683,
                "longitude" => 105.84201921655531,
                "created_at" => (new DateTime())->modify("- 20 days"),
                "updated_at" => (new DateTime())->modify("- 20 days"),
            ],
            [
                'user_id' => 3,
                'title' => "Cho thuê căn hộ 2 phòng ngủ đẹp gần Vincom Times City",
                "address" => "22 ngõ 35 Minh Khai, Trương Định, Hai Bà Trưng, Hà Nội",
                "street" => "35 Minh Khai",
                "ward" => "Trương Định",
                "district" => "Hai Bà Trưng",
                "price" => 8000000,
                "land_area" => 50,
                "type" => 2,
                "view_number" => 310,
                "description" => "Căn hộ 2 phòng ngủ gần Vincom Times City. Diện tích 50m², nội thất đẹp, view đẹp. Giá thuê 8 triệu/tháng.",
                "bedroom_num" => 2,
                "bathroom_num" => 1,
                "latitude" => 20.99683353542686,
                "longitude" => 105.85141107516783,
                "created_at" => (new DateTime())->modify("- 22 days"),
                "updated_at" => (new DateTime())->modify("- 22 days"),
            ],
            [
                'user_id' => 4,
                'title' => "Cho thuê nhà nguyên căn gần trường THPT Trần Phú",
                "address" => "39 ngõ 87 Lê Ngọc Hân, Ngô Thì Nhậm, Hoàn Kiếm, Hà Nội",
                "street" => "87 Lê Ngọc Hân",
                "ward" => "Ngô Thì Nhậm",
                "district" => "Hoàn Kiếm",
                "price" => 6000000,
                "land_area" => 45,
                "type" => 2,
                "view_number" => 270,
                "description" => "Nhà nguyên căn gần trường THPT Trần Phú. Diện tích 45m², đầy đủ tiện nghi. Giá thuê 6 triệu/tháng.",
                "bedroom_num" => 2,
                "bathroom_num" => 2,
                "latitude" => 21.01616831278715,
                "longitude" => 105.85543763039793,
                "created_at" => (new DateTime())->modify("- 25 days"),
                "updated_at" => (new DateTime())->modify("- 25 days"),
            ],
            [
                'user_id' => 5,
                'title' => "Cho thuê căn hộ mini gần trường Đại học Kinh tế Quốc dân",
                "address" => "12 ngõ 56 Lạc Trung, Thanh Lương, Hai Bà Trưng, Hà Nội",
                "street" => "56 Lạc Trung",
                "ward" => "Thanh Lương",
                "district" => "Hai Bà Trưng",
                "price" => 4500000,
                "land_area" => 28,
                "type" => 3,
                "view_number" => 200,
                "description" => "Căn hộ mini gần trường Đại học Kinh tế Quốc dân. Diện tích 28m², nội thất đầy đủ. Giá thuê 4.5 triệu/tháng.",
                "bedroom_num" => 1,
                "bathroom_num" => 1,
                "latitude" => 21.00317467763041,
                "longitude" => 105.86287304216197,
                "created_at" => (new DateTime())->modify("- 27 days"),
                "updated_at" => (new DateTime())->modify("- 27 days"),
            ],
            [
                'user_id' => 6,
                'title' => "Cho thuê phòng trọ mới xây gần chợ Đồng Xuân",
                "address" => "18 ngõ 72 Hàng Bồ, Hàng Bồ, Hoàn Kiếm, Hà Nội",
                "street" => "72 Hàng Bồ",
                "ward" => "Hàng Bồ",
                "district" => "Hoàn Kiếm",
                "price" => 3200000,
                "land_area" => 18,
                "type" => 1,
                "view_number" => 180,
                "description" => "Phòng trọ mới xây gần chợ Đồng Xuân. Diện tích 18m², sạch sẽ, gần các tiện ích. Giá thuê 3.2 triệu/tháng.",
                "bedroom_num" => 1,
                "bathroom_num" => 1,
                "latitude" => 21.033995873152374,
                "longitude" => 105.8485186722614,
                "created_at" => (new DateTime())->modify("- 30 days"),
                "updated_at" => (new DateTime())->modify("- 30 days"),
            ],
            [
                'user_id' => 7,
                'title' => "Cho thuê nhà riêng 3 tầng gần khu vực Vincom Times City",
                "address" => "9 ngách 45 ngõ 74 Phố Mai Động, Mai Động, Hai Bà Trưng, Hà Nội",
                "street" => "74 Mai Động",
                "ward" => "Mai Động",
                "district" => "Hai Bà Trưng",
                "price" => 7000000,
                "land_area" => 40,
                "type" => 2,
                "view_number" => 220,
                "description" => "Nhà riêng 3 tầng gần khu vực Vincom Times City. Diện tích 40m², đầy đủ tiện nghi. Giá thuê 7 triệu/tháng.",
                "bedroom_num" => 2,
                "bathroom_num" => 2,
                "latitude" => 20.990276170027524,
                "longitude" => 105.86144322672477,
                "created_at" => (new DateTime())->modify("- 32 days"),
                "updated_at" => (new DateTime())->modify("- 32 days"),
            ],
            [
                'user_id' => 8,
                'title' => "Cho thuê phòng trọ mới xây gần trường THPT Vân Đồn",
                "address" => "15 ngõ 63 Điện Biên Phủ, Điện Biên, Ba Đình, Hà Nội",
                "street" => "63 Điện Biên Phủ",
                "ward" => "Điện Biên",
                "district" => "Ba Đình",
                "price" => 3000000,
                "land_area" => 20,
                "type" => 1,
                "view_number" => 150,
                "description" => "Phòng trọ mới xây gần trường THPT Vân Đồn. Diện tích 20m², sạch sẽ, gần trường học. Giá thuê 3 triệu/tháng.",
                "bedroom_num" => 1,
                "bathroom_num" => 1,
                "latitude" => 21.02952010969744,
                "longitude" => 105.84234257002333,
                "created_at" => (new DateTime())->modify("- 35 days"),
                "updated_at" => (new DateTime())->modify("- 35 days"),
            ],
            [
                'user_id' => 9,
                'title' => "Cho thuê căn hộ cao cấp gần Vinhomes Times City",
                "address" => "10 ngõ 5 Lĩnh Nam, Mai Động, Hoàng Mai, Hà Nội",
                "street" => "5 Lĩnh Nam",
                "ward" => "Mai Động",
                "district" => "Hai Bà Trưng",
                "price" => 9000000,
                "land_area" => 65,
                "type" => 2,
                "view_number" => 380,
                "description" => "Căn hộ cao cấp gần Vinhomes Times City. Diện tích 65m², nội thất sang trọng. Giá thuê 9 triệu/tháng.",
                "bedroom_num" => 2,
                "bathroom_num" => 2,
                "latitude" => 20.991736228513243,
                "longitude" => 105.86460340045802,
                "created_at" => (new DateTime())->modify("- 38 days"),
                "updated_at" => (new DateTime())->modify("- 38 days"),
            ],
            [
                'user_id' => 10,
                'title' => "Cho thuê nhà riêng 4 tầng gần công viên Thống Nhất",
                "address" => "25 ngách 18 ngõ 35 Trần Nhân Tông, Bùi Thị Xuân, Hai Bà Trưng, Hà Nội",
                "street" => "35 Trần Nhân Tông",
                "ward" => "Bùi Thị Xuân",
                "district" => "Hai Bà Trưng",
                "price" => 8000000,
                "land_area" => 55,
                "type" => 2,
                "view_number" => 270,
                "description" => "Nhà riêng 4 tầng gần công viên Thống Nhất. Diện tích 55m², đầy đủ tiện nghi. Giá thuê 8 triệu/tháng.",
                "bedroom_num" => 3,
                "bathroom_num" => 3,
                "latitude" => 21.017062612344123,
                "longitude" => 105.8504039015074,
                "created_at" => (new DateTime())->modify("- 40 days"),
                "updated_at" => (new DateTime())->modify("- 40 days"),
            ],
        ]);
    }
}
